### ISSUE TITLE
Provide UI page to support profile view, edit and delete

### ISSUE THREAD

**Issue by izrake** [argoapp-live/argo-react#10]
There will be the following user interaction on the UI:
- There will be a need for settings that will contain the profile details in an editable state.
- The fields shown are: 
   - username
   - name
   - avatar
- Every field should be individually saved.
- The Deactivate/Delete button should be on the same page with a warning message written on it.

**Comment by rekpero** [comment]
Done from the UI side.
Integrated with the API.
Need an end to end testing @izrake

**Comment by rekpero** [comment]
Closing this issue and Tested E2E.
