### ISSUE TITLE
Make header nav bar sticky

### ISSUE THREAD

**Issue by rekpero** [argoapp-live/argo-react#18]
## Issue Description

Currently, our navbar below the header is static and the user has to come back up to navigate to other tabs. 
We would like to see the navbar gets sticky (ie gets fixed at the top) as the user goes down and the navbar touches the top. Also, the Argo logo must be there on the left side of the navbar as the user go down and the transition should be smooth as well.

![image](https://user-images.githubusercontent.com/34746546/96290462-4183c380-1004-11eb-972b-4d672d641d25.png)

## Contact
Please ping us on discord to know more about this issue -  https://discord.gg/HTMqYAm

**Comment by asharonbaltazar** [comment]
Hello, I'd like to help. Currently, there's no content on the screen for a `sticky` navbar to make a difference. How would you like to implement it?

**Comment by rekpero** [comment]
Hey @asharonbaltazar Glad that you want to contribute to ArGo. Please join our discord server, we can continue there:
Link to ArGo discord server: https://discord.gg/B53AvKK
